USERNAME_PATTERN = r'^[\w.@+-]+\Z'
USERNAME_MAX_LENGTH = 150
EMAIL_MAX_LENGTH = 254
CHARFIELD_MAX_LENGTH = 150
SLUGFIELD_MAX_LENGTH = 150
MAX_LENGTH_COLOR = 7
MAX_LENGTH_INGREDIENT_NAME = 128
MAX_LENGTH_MEASUREMENT_UNIT = 64
